language: c

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libopenmpi-dev
      - libmetis-dev
      - libunittest++-dev

env:
  global:
    - CCACHE_CPP2=yes
  matrix:
    - PARALLEL=yes

script:
  - >
     ls /usr/include/UnitTest++.* &&
     mkdir build && cd build && echo "PARALLEL = $PARALLEL" &&
     CC=mpicc cmake -DENABLE_ExodusII=no
     -DINSTALL_ADD_VERSION=no
     -DENABLE_PARALLEL=$PARALLEL
     -DENABLE_METIS=yes
     -DMETIS_INCLUDE_DIR=/usr/include
     -DENABLE_Tests=no
     -DUnitTest_DIR:FILEPATH=/usr/include 
     .. && 
     make -j2 && make install DESTDIR=$HOME

cache:
  - ccache

compiler:
  - gcc
