language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - libmetis-dev
      - libunittest++-dev
env:
  global:
    - CCACHE_CPP2=yes
  matrix:
    - PARALLEL=ON
    - PARALLEL=OFF

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

before_script:
  - cmake --version
  - mpirun --version
  - mpiexec --version


after_failure:
  - echo $TRAVIS_TEST_RESULT
  - cat Testing/Temporary/LastTest.log

script:
  - >
     mkdir build &&
     cd build &&
     cmake 
     -DCMAKE_C_COMPILER:FILEPATH=`which mpicc`
     -DCMAKE_CXX_COMPILER:FILEPATH=`which mpiCC`
     -DCMAKE_BUILD_TYPE=Release
     -DINSTALL_ADD_VERSION=no
     -DENABLE_PARALLEL=$PARALLEL
     -DENABLE_METIS=yes
     -DMETIS_INCLUDE_DIR=/usr/include
     -DENABLE_ExodusII=OFF
     -DENABLE_Tests=yes
     -DUnitTest_DIR:FILEPATH=/usr/include/unittest++
     ..    && 
     make -j2 
  -  mpiexec --version 
  -  mpiexec -n 4 utils/meshconvert/meshconvert 
  -  mpiexec -np 4 utils/meshconvert/meshconvert 
  -  mpiexec -np 1 utils/meshconvert/meshconvert 
  -  make test 
  -  ctest
  -  make install DESTDIR=$HOME

cache:
  - ccache

compiler:
  - gcc
  - clang
