language: c

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libopenmpi-dev
      - libmetis-dev
      - libunittest++-dev

env:
  global:
    - CCACHE_CPP2=yes
  matrix:
    - PARALLEL=yes

script:
  - >
     mkdir build &&
     cd build &&
     ls /usr/bin/mpi* &&
     cmake 
     -DCMAKE_C_COMPILER:FILEPATH=`which mpicc`
     -DCMAKE_CXX_COMPILER:FILEPATH=`which mpiCC`
     -DCMAKE_BUILD_TYPE=Release
     -DINSTALL_ADD_VERSION=no
     -DENABLE_PARALLEL=$PARALLEL
     -DENABLE_METIS=yes
     -DMETIS_INCLUDE_DIR=/usr/include
     -DENABLE_ExodusII=no
     -DENABLE_Tests=yes
     -DUnitTest_DIR:FILEPATH=/usr/include/unittest++
     ..    && 
     make -j2 &&
     make test &&
     make install DESTDIR=$HOME

cache:
  - ccache

compiler:
  - gcc
