language: c

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - debian-sid
    packages:
#      - libopenmpi-dev
#      - openmpi-bin
      - libopenmpi1.6
      - libmetis-dev
      - libunittest++-dev
env:
  global:
    - CCACHE_CPP2=yes
  matrix:
    - PARALLEL=ON
    - PARALLEL=OFF

before_install:
  - sudo apt search openmpi
  - sudo apt search libopenmpi-dev
  - sudo apt search openmpi-bin
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

after_failure:
  - echo $TRAVIS_TEST_RESULT
  - cat Testing/Temporary/LastTest.log

script:
  - >
     mkdir build &&
     cd build &&
     cmake 
     -DCMAKE_C_COMPILER:FILEPATH=`which mpicc`
     -DCMAKE_CXX_COMPILER:FILEPATH=`which mpiCC`
     -DCMAKE_BUILD_TYPE=Release
     -DINSTALL_ADD_VERSION=no
     -DENABLE_PARALLEL=$PARALLEL
     -DENABLE_METIS=yes
     -DMETIS_INCLUDE_DIR=/usr/include
     -DENABLE_ExodusII=OFF
     -DENABLE_Tests=yes
     -DUnitTest_DIR:FILEPATH=/usr/include/unittest++
     ..    && 
     make -j2 &&
     mpirun --version &&
     make test &&
     make install DESTDIR=$HOME

cache:
  - ccache

compiler:
  - gcc
  - clang
